### ISSUE TITLE
Trouble rendering in Sketch

### ISSUE THREAD

**Issue by msteinmn** [seek-oss/seek-style-guide#553] opened 2018-10-11 10:24 UTC
This project is a wonderful idea to streamline developer - designer interaction. I struggle getting it to render in Sketch: 

- It builds successfully running npm run test
- It creates two asketch files in /dist/asketch
          -rw-r--r--  1 user  staff    15654 Oct 11 11:15 document.asketch.json
          -rw-r--r--  1 user  staff  2405555 Oct 11 11:15 page.asketch.json
- Using Sketch 52.1, now 52.2, asketch2sketch plugin 4.0.0, no other plugins or libraries
- Create a new document in Sketch
- Import files using plugin, either document or page first, or both selected at the same time

It creates a page entry 'html-sketchapp-symbols' in the left navigation. The Sketch page remains empty. There are no new symbols or anything. Either I must be missing something fundamental, or there is an issue with this version of Sketch. Any suggestions would be great.

**Comment by markdalgleish** [comment] 2018-10-18 04:06
This repo is still on an older version of html-sketchapp, so it's probably clashing with your plugin. I can't reproduce this, so closing for now.

**Closed by markdalgleish** 2018-10-18 04:06 UTC
