### ISSUE TITLE
Autosuggest styling broken

### ISSUE THREAD

**Issue by LeviSeek** [seek-oss/seek-style-guide#258] opened 2017-07-24 07:06 UTC
if there are 2 text fields(in this case, job title/company name) with autosuggest, the styling for the 1st autosuggest list will be broken.

![image](https://user-images.githubusercontent.com/16127935/28511785-1255fba6-7092-11e7-880c-0e53e5ba5e1c.png)

**Comment by georgespyropoulos** [comment] 2017-07-24 23:43
Looks like the issue is that the z-index on the `.suggestionsContainer` class was removed in this PR https://github.com/seek-oss/seek-style-guide/pull/241/files

**Comment by kosanna** [comment] 2017-07-25 00:45
Looking

**Comment by kosanna** [comment] 2017-07-25 00:47
Hm...@georgespyropoulos it should not be an issue as it's been transferred to a higher level container

**Comment by kosanna** [comment] 2017-07-25 00:57
Will do a fix in a sec

**Comment by markdalgleish** [comment] 2017-07-27 07:16
Looks like this is fixed, so closing the issue.

**Closed by markdalgleish** 2017-07-27 07:16 UTC
